name: Snapshot

on: workflow_dispatch

permissions: {}

jobs:
  publish:
    name: Publish Snapshot
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.SEEK_OSS_CI_GITHUB_TOKEN }}

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
          package-manager-cache: false

      - name: Set up pnpm
        run: corepack enable pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish to npm
        uses: seek-oss/changesets-snapshot@v0
        env:
          GITHUB_TOKEN: ${{ secrets.SEEK_OSS_CI_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
